### ISSUE TITLE
Huge memory allocations

### ISSUE THREAD

**Issue by Molkree** [ooipy/ooipy#100] opened 2021-09-20 20:22 UTC
I've just hit an unfortunate situation where OOIPy blows up RAM usage when getting one second of data.
Minimal reproducible example:
```py
import datetime

from ooipy.request import hydrophone_request

start_time_str = "2021-09-19T12-16-49"
end_time_str = "2021-09-19T12-16-50"
node = "PC01A"

start_time = datetime.datetime.strptime(start_time_str, "%Y-%m-%dT%H-%M-%S")
end_time = datetime.datetime.strptime(end_time_str, "%Y-%m-%dT%H-%M-%S")

hydrophone_data = hydrophone_request.get_acoustic_data(
    start_time, end_time, node, verbose=True
)
```

In [Google Colab](https://colab.research.google.com/drive/1yUlELpghbq-HLtRApEUqrlCQMWZMq8j9?usp=sharing) I see ~10GB allocation and then one more ~10GB which crashes the kernel.

![image](https://user-images.githubusercontent.com/12860284/134070318-325fa269-30d1-4274-912e-31756d58aa81.png)

The same thing crashed our processing in [GitHub VMs](https://github.com/orcasound/orca-action-workflow/issues/56).

Here's why I narrowed it down to just one second of data:
![image](https://user-images.githubusercontent.com/12860284/134069997-7a5e8da9-bb9d-4304-96a1-b986df72573c.png)

**Comment by John-Ragland** [comment] 2022-09-23 19:42
I think that this issue is caused by how data is organized from OOI's side of things. They have actually since fixed each mseed file to be 5 minutes (and they are doing some type of gap filling).

I'm closing this for now.

**Closed by John-Ragland** 2022-09-23 19:42 UTC
